### ISSUE TITLE
라커 - 서버간 통신 API 설계

### ISSUE THREAD

**Issue by ndkim11** [osamhack2020/WEB_LeaveItUs_797IsPalindrome#2]
생활관별로 
1)int 형 3X7 행렬로 행= 금일 영내인 병사 여부(0/1), 무게, 반납여부(0/1) 형태. 
2)String 형의 등록된 태그를 최대 7개 담은 RegisteredRFtag[7]
이것을 어디 배열 같은데에 각 생활관 인덱스에 저장해서 전달해줄 수 있을까.
ex) int 1PhoneStatus[3][7];
      int 2PhoneStatus[3][7];
      int * HolderPtrArray[12] = [1PhoneStatus, 2PhoneStatus, ...]
      String RegisteredRFtag[7] = {3E 12 21 14 11 A4, ...}
이렇게 전달 받으면 게이트웨이에서 byte RoomNum = index + 1; 이런식으로 생활관 번호랑 그에 따른 상태(status), tag를 판단할 수 있을듯.
이거가 별로면 내가 방법은 사실 정확히 판단해놓지는 않았지만 생활관 별로 전송을 하는거지. 1 보내고 2 보내고 ...

**Comment by Dictor** [comment]
@ndkim11 내가 생각한것도 뭐 비슷하긴 한데, 영내 병사 여부를 서버에서 라커로 보내서 처리하려고 하면 괜히 라커에서 처리하는 정보 양이랑 복잡도만 늘어나는거 같아서, 다음 두가지 행동만 하는 게 간단하고 상태 관리하기도 좋을 듯.
API 모두 모아서 문서화할테지만, 일단 라커 입장에선 두 개만 쓰자고. 

## 데이터 정의
[구현에 사용되는 데이터의 상세 정의는 여기](https://github.com/osamhack2020/WEB_LeaveItUs_797IsPalindrome/blob/master/backend/model.go)

방 ID : 생활관의 ID, 동일한 서버를 사용하는 생활관과 인력을 정의할 때 **유일**해야함. **출력 가능한 ASCII 문자열**로 구성.
라커 UID: 라커 기기의 고유 ID, 라커를 구분하는데 사용함으로 존재하는 모든 라커 기기에 대해서 **유일**해야 함. **출력 가능한 ASCII 문자열**로 구성.
태그 UID: 태그의 고유 ID, 태그를 구분하는데 사용함으로 존재하는 모든 NFC 태그에 대해서 **유일**하며 불변해야함.

## 자신의 방 ID 및 소속 핸드폰 목록 가져오기
- 요청 : 라커가 자신의 UID를 포함하여 핸드폰 목록을 요청  
- 처리 : 서버는 라커의 UID로 라커의 소속 방 ID를 DB에서 가져오고, 해당 방에 소속된 휴대폰 목록을 전부 가져옴.
- 응답 : 서버는 휴대폰 목록에서 태그 UID를 추출하여 라커에게 방 ID와 태그 UID의 배열을 전송함.
- 동작 : 라커는 받은 태그 UID를 기준으로 올바른 휴대폰 반납/불출을 관리하며 반납된 휴대폰 목록을 관리함

## 현재 자신에게 보관된 핸드폰 목록 보내기
- 요청 : 일정 주기마다 라커가 자신의 UID와 현재 자신이 보관하고 있는 태그 UID의 배열을 요청. 
- 처리 : 서버는 라커 UID로 방 ID, 휴대폰 목록을 유추하고 태그 UID 배열을 통해 반납 현황을 갱신 함.
- 응답 : 오류가 발생하지 않는 이상 별도 응답 없음. 라커 입장에서는 요청 후 망각하면 됨.

**모든 데이터 교환은 JSON을 통해서**

**Comment by ndkim11** [comment]
@Dictor 그니까 보관함에서 하는 일은 
1. 서버에 자기 UID랑 태그 목록을 **요청**하고 받은 태그 목록을 가지고 올바른 휴대폰이 반납됐는지 **보관함에서** 처리하는 거지? 
2. 서버에 자신의 UID랑 보관함에서 처리한 반납된 휴대폰 **태그**목록을 보내고 서버는 받은 목록에 있는 반납된 휴대폰들의 태그를 읽고 반납 현황을 갱신하는 거지?

내가 할려던건 byte RoomNum = 12; 이런식으로 방 번호를 미리 정해 놓고 게이트웨이에서는 이 방 번호에 맞게 목록을 쪼개서 보관함에 분배해줄려고 했음. 근데 방의 ID랑 보관함의 UID가 따로 필요한 이유는 뭐야? 어떻게 서버에서 각 보관함에 맞는 UID를 나눠줄 수 있는지 잘 감이 안잡히네

**Comment by ndkim11** [comment]
[holder.ino](https://github.com/osamhack2020/IoT_LeaveItUs_797IsPalindrome/blob/master/ArduinoCode/holder.ino)
혹시라도 시간이 나서 여기 볼 수 있다면 보관함과 게이트웨이 마다 0~65535 사이의 주소값을 다르게 할당해주고 AT+(게이트웨이 주소) 로 해서 게이트웨이에 데이터를 보낼 계획이었음
그리고 tast4가 데이터를 받아오는 테스크인데, 여기서 오늘 시리얼 명령에  InSerialStr.startsWith("Update PhoneStatus:") 이런 식으로 해서 명령을 구분할려고 했었음.
코드 보고 혹시 좋은 방법 생각나는거 있으면 말해줄 수 있냐? 코드 읽기 좀 많으면  그냥 전화해서 코드 설명 물어보면 내가 알려주고ㅇㅇ

**Comment by Dictor** [comment]
@ndkim11 
> 1. 서버에 자기 UID랑 태그 목록을 **요청**하고 받은 태그 목록을 가지고 올바른 휴대폰이 반납됐는지 **보관함에서** 처리하는 거지?
> 2. 서버에 자신의 UID랑 보관함에서 처리한 반납된 휴대폰 **태그**목록을 보내고 서버는 받은 목록에 있는 반납된 휴대폰들의 태그를 읽고 반납 현황을 갱신하는 거지?   

오키 이건 이해한게 맞아.

> 내가 할려던건 byte RoomNum = 12; 이런식으로 방 번호를 미리 정해 놓고 게이트웨이에서는 이 방 번호에 맞게 목록을 쪼개서 보관함에 분배해줄려고 했음. 근데 방의 ID랑 보관함의 UID가 따로 필요한 이유는 뭐야? 

맞아, 이건 조금 의아하게 생각할 수도 있는 부분이긴해. 왜 이렇게 서버에서 중앙집중적으로 데이터 관리를 몰아서 하게 설계했느냐 하면, 결국 서버와 하드웨어 어디든지 하나는 입력된 방대한 데이터를 처리해야한다면 그나마 데이터를 더 수정하기 어려운 쪽, 하드웨어를 최대한 **무상태(Stateless)** 지향적으로 설계하려고 그런거임.

예를 들어서, 12개방에 12개 라커가 잘 붙어있다고 생각해보자. 한자기 시나리오를 생각해볼께,
**어떤 하나의 방의 라커가 고정나서 라커를 교체해야하는 상황**에서,  교체해야하는 방을 예상할 수가 없으니 소요가 발생하는 바로 그때 [방번호=방 ID](https://github.com/osamhack2020/IoT_LeaveItUs_797IsPalindrome/blob/bb15289bee89101f4eab45354d9823def989a555/ArduinoCode/holder.ino#L34)를 바꿔서 기기를 재 프로그래밍해야 할텐데, (여기서 방 ID가 기기가 미리 들고있어야 하는 **상태(State)**) 말단 부대에서 기기를 USB로 연결해서 아두이노 깔고 소스를 빌드해서 다운로드하는데 많은 애로사항이 생길거 같다고 생각해. (너도 공병하면서 수리 접수 해봐서 잘 알겠지만) 또 방 ID가 겹치거나 위조된다든가 하는 기술적인 문제는 차지해도. 
**하지만** 단지 라커는 제작될때 입력된 UID만 들고 있다가 UID를 기반으로 서버에 자신을 알리고 들고있는 핸드폰을 보고한다면, 간단히 서버의 웹 UI에서 방 ID와 연결된 라커의 UID만 변경해주면 이걸로 기기 교체 작업은 끝나는거지. 즉, UID를 제외한 여타 모든 상태들은 서버에서 관리하는거지. 물론 전자의 방법보다 훨씬 편리하기도 하고.

**Comment by Dictor** [comment]
> 어떻게 서버에서 각 보관함에 맞는 UID를 나눠줄 수 있는지 잘 감이 안잡히네

이 UID는 IMEI같은거라 생각하면 편할듯, 이것도 발급시 몇가지 방법이 있는데,
- 처음 프로그램되서 공장에 출고할때 플래시에 상수로 고유 아이디를 넣어준다 : 아두이노만 있으면 되고 젤 편리하지만 이러면 소스에 상태 의존성이 생겨. 즉 다운로딩할때 그냥 다운로드 버튼만 누르면 되는게 아니라 UID 발급 로직도 구현해줘야지. 물론 아두이노의 플래시야 RW가 모두 가능하니까 UID를 위조하거나 복제할수도 있어서 엄밀성이나 보안성이 떨어지기도 해.
- EEPROM을 활용한다 : 이것도 위 플래시 방법이랑 장단점은 비슷할거 같아.
- ROM이나 고유 부품을 사용한다 :  [이런 부품](https://www.microchip.com/wwwproducts/en/AT21CS01)을 이용해서 하드웨어적으로 고유 ID를 관리할수도 있어. 이러면 소스에 UID 의존성이 사라지고 위조나 복제하려면 직접 하드웨어를 까야해, 물론 복잡성이나 가격은 올라가지.

**Comment by ndkim11** [comment]
> **하지만** 단지 라커는 제작될때 입력된 UID만 들고 있다가 UID를 기반으로 서버에 자신을 알리고 들고있는 핸드폰을 보고한다면

내가 잘못 이해한듯. 난또 서버에서 라커들한테 매번 UID를 재할당해준다는 말로 이해했음
