### ISSUE TITLE
Person 및 Room 모델 관계 변경 필요

### ISSUE THREAD

**Issue by Dictor** [osamhack2020/WEB_LeaveItUs_797IsPalindrome#3]
Room 모델이 Person을 열거하기 보다는, Person에 소속 Room을 정의하고 Room은 Person과의 연관성을 삭제하는게 좋을 듯.

**Comment by ndkim11** [comment]
흠 그러면 게이트웨이에서 어떤 식으로 데이터를 보내주면 되는거지? 폰 받고 전화 한번만 해줘

**Comment by Dictor** [comment]
@ndkim11 이거는 서버 내부에서 데이터 연관 관계를 역전시킨거라 내부에서 처리하는 방식만 바뀌어서, 게이트웨이 입장에서는 변화없을듯!
