### ISSUE TITLE
제출 자료 준비

### ISSUE THREAD

**Issue by Dictor** [osamhack2020/WEB_LeaveItUs_797IsPalindrome#4]
- [x] 웹 MVP (시연)
- [x] 하드웨어 MVP (시연 불가, 코드와 회로도, 모델링)
- [x] 시연 영상
- [ ] 발표 자료

**Comment by Dictor** [comment]
**발표 자료 내용** 
_S_ :  상윤 _J_ : 정현 _A_ : 모두
- [x]  목차  _A_ 
- [x]  팀원 소개 및 역할 _A_
- [x]  개발 동기 (현실태 → 문제 상황 → 해결 방안) _J_
- [x]  해결 방안에 따른 장치 핵심 기능과 설계 (다이어그램) _J_
- [ ]  장치 세부 구성 (회로도, 모델링) _S_ 
- [x]  개발 중점 _A_
- [x]  목표 시장과 기대효과, 군에 적용가능성  _A_
- [x]  기존 방식에 대한 차별점, 강점 _A_
- [ ]  애로사항과 개선할 점 _A_

**Comment by Dictor** [comment]
다이어그램에 자료 모델 및 흐름도 필요

- 상윤이는 
- [ ] 회로도 (브레드보드 그거 말고)
- [x] 모델링 (렌더링 된 이미지 파일이나 캡처)
- [ ] 아두이노 코드 흐름을 설명하는 흐름도 제작해줄 것 (슬라이드의 코드 대신)
- [x] 코드는 컴파일 확인
- [ ] IoT 분야에서 애로사항 개선할점, 아쉬운 점
- [ ] IoT 개발중점 (어떤 문제가 예상되서 어떻게 대처했다)
- [ ] 문서 추가
@ndkim11

**Comment by Dictor** [comment]
해결 방안의 기능 설계 언급하고 실제로 어떻게 사용되는지 워크플로우도 삽입

**Comment by ndkim11** [comment]
연결도만 제작된 상태인데, 회로도는 제작해야됨

**Comment by Dictor** [comment]
@ndkim11 
발표자료 구글 드라이브 ndkim11@지메일로 공유 걸어놓았고, 
일단 위에 언급된 제작할 사항 제작해주면 되고,
진행 상황 커밋이나 이슈로 자주자주 업데이트 해주면 고맙!!

**Comment by ndkim11** [comment]
나 구글은 ndkim12라서 그런가 공유 링크가 없던데. 지금 flowchart하는 중임

**Comment by Dictor** [comment]
> 나 구글은 ndkim12라서 그런가 공유 링크가 없던데. 지금 flowchart하는 중임

다시 초대 했디
